---
- name: Configure Puma App
  hosts: app
  become: true

  vars:
    db_host: reddit-db

  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config from DB connection
      template:
        src: templates/db_config.j2
        dest: /home/andrey/db_config
        owner: andrey
        group: andrey

    - name: Enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      systemd:
        name: puma
        state: restarted
