plugin: gcp_compute
projects:
  - infra-311816
zones:
  - "europe-west3-a"
hostnames:
  - "public_ip"
auth_kind: serviceaccount
service_account_file: "/home/andrey/courses-train/everyandrey_infra/infra-311816-b53635ac6f21.json"
